# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Upload the production build to the app store"
  lane :upload_to_appstore do |options|
    asc_key_content = ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    asc_issuer_id = ENV["APP_STORE_CONNECT_ISSUER_ID"]
    asc_key_id = ENV["APP_STORE_CONNECT_API_KEY_ID"]
  
    app_store_connect_api_key(
      key_id: asc_key_id,
      issuer_id: asc_issuer_id,
      key_content: asc_key_content
    )
    
    deliver(
      ipa: options[:ipa],
      submit_for_review: true,
      automatic_release: true,
      force: true, 
      precheck_include_in_app_purchases: false,
      app_identifier: options[:bundle_id],
      submission_information: { add_id_info_uses_idfa: false }
    )      

  end
end

